 
version: "2"
services:

  web:
    container_name: socle-meteor-itg
    build: .
    ports:
        - "8041:3000"
    links:
        - database
    environment:
        - METEOR_ALLOW_SUPERUSER=true
        - ROOT_URL=http://example.com
        - MONGO_URL=mongodb://database:27017/meteor
    networks:
      app_net:
        ipv4_address: 10.4.2.2

  database:
    container_name: socle-meteor-database-itg
    image: mongo
    ports:
        - "3351:27017"
    command: mongod --smallfiles --quiet --logpath=/dev/null
    networks:
      app_net:
        ipv4_address: 10.4.2.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.4.2.0/24
        gateway: 10.4.2.1

